import {StyleSheet} from 'react-native';
import {colors, fonts, perfectSize, width} from '../../theme';

// eslint-disable-next-line no-undef
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundColor,
  },
  skeletonContainer: {
    flex: 1,
    backgroundColor: colors.backgroundColor,
    // alignItems: 'center',
  },
  headerContainer: {
    flexDirection: 'row',
    marginTop: perfectSize(10),
    paddingLeft: perfectSize(23),
  },
  headerTitleContainer: {},
  headerTitle: {
    color: colors.headerTitleColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(30),
  },
  userName: {
    color: colors.headerTitleColor,
    fontFamily: fonts.quicksandRegular,
    fontSize: perfectSize(23),
    marginTop: perfectSize(10),
    letterSpacing: perfectSize(1),
  },
  filterContainer: {
    width: '100%',
    paddingLeft: perfectSize(23),
    paddingRight: perfectSize(23),
    marginTop: perfectSize(23),
    // justifyContent: 'space-between',
    marginBottom: '5%',
    // flexDirection: 'row',
  },
  filterInnerContainer: {
    width: '100%',
    justifyContent: 'space-between',
    // marginBottom: '5%',
    flexDirection: 'row',
  },
  filterButtonContainer: {
    height: perfectSize(40),
    width: '30%',
    // backgroundColor: colors.primaryCardBackgroundColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: perfectSize(10),
  },
  filterButtonTitle: {
    fontSize: perfectSize(15),
    color: colors.primaryLightColor,
    fontFamily: fonts.avenirHeavy,
    fontWeight: 'bold',
  },
  dateLabel: {
    textAlign: 'center',
    marginTop: '5%',
    color: colors.primaryLightColor,
    opacity: 0.5,
    fontFamily: fonts.quicksandBold,
    textDecorationLine: 'underline',
    fontSize: perfectSize(18),
  },
  scrollContainer: {
    flex: 1,
    paddingLeft: perfectSize(23),
    paddingRight: perfectSize(23),
  },
  dashboardContainer: {
    width: '100%',
    alignSelf: 'center',
    borderRadius: perfectSize(20),
    backgroundColor: colors.primaryCardBackgroundColor,
    justifyContent: 'center',
    padding: perfectSize(20),
  },
  myBalanceTitle: {
    fontSize: perfectSize(16),
    fontFamily: fonts.avenirMedium,
    color: colors.primaryLightColor,
    opacity: 0.7,
    letterSpacing: perfectSize(0.5),
  },
  myBalanceStyle: {
    fontSize: perfectSize(26),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
  },
  dashboardInnerContainer: {
    width: '70%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '5%',
  },
  incomeContainer: {
    width: '50%',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  expenseContainer: {
    width: '50%',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  dashboardIncomeHeaderStyle: {
    fontSize: perfectSize(16),
    fontFamily: fonts.avenirMedium,
    color: colors.primaryLightColor,
    opacity: 0.7,
    letterSpacing: perfectSize(0.5),
  },
  dashboardExpenseHeaderStyle: {
    fontSize: perfectSize(16),
    fontFamily: fonts.avenirMedium,
    color: colors.primaryLightColor,
    opacity: 0.7,
    letterSpacing: perfectSize(0.5),
  },
  dashboardIncomeStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(22),
  },
  dashboardExpenseStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(22),
  },
  dashboardImage: {
    height: '90%',
    width: '60%',
    position: 'absolute',
    resizeMode: 'contain',
    top: '5%',
    right: '2%',
  },
  topCatContainer: {
    marginTop: '7%',
  },
  catHeaderContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  seeAllContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  seeAllTitle: {
    color: colors.headerTitleColor,
    fontFamily: fonts.avenirMedium,
    fontSize: perfectSize(14),
  },
  topCatHeader: {
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
  },
  expenseCatContainer: {
    alignItems: 'center',
    backgroundColor: colors.primaryCardBackgroundColor,
  },
  //Category list styles
  catContainer: {
    height: perfectSize(200),
    width: '47.77%',
    alignItems: 'center',
    borderRadius: perfectSize(20),
  },
  catImageContainer: {
    height: '50%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  catImage: {
    marginTop: '10%',
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    // tintColor: colors.primaryLightColor,
  },
  catTitle: {
    marginTop: '10%',
    fontSize: perfectSize(18),
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
  },
  catTotalExpense: {
    fontSize: perfectSize(18),
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
  },
  recentTransactionsListContainer: {
    width: '100%',
    marginTop: '5%',
    alignSelf: 'center',
    borderRadius: perfectSize(20),
    justifyContent: 'center',
    marginBottom: '10%',
  },
  recentTransactionsHeader: {
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
  },
  //Recent transactions style
  recentTransactionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: perfectSize(10),
    marginTop: perfectSize(15),
    padding: '5%',
    // backgroundColor: colors.secondaryCardBackgroundColor,
  },
  recentTransactionsImageContainer: {
    height: perfectSize(70),
    width: perfectSize(70),
    borderRadius: perfectSize(35),
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentTransactionsImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
  },
  recentTransactionsDetailsContainer: {
    marginLeft: '5%',
  },
  recentTransactionsTitle: {
    color: colors.primaryLightColor,
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    width: '80%',
  },
  recentTransactionsDate: {
    color: colors.primaryLightColor,
    fontSize: perfectSize(15),
    fontFamily: fonts.quicksandBold,
    opacity: 0.7,
    marginTop: '6%',
  },
  recentTransactionsAmount: {
    // color: colors.primaryLightColor,
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    right: '4%',
    position: 'absolute',
  },
  //Date picker modal styles
  modal: {
    flex: 1,
    alignItems: 'center',
  },
  modalViewContainer: {
    flex: 1,
    backgroundColor: colors.modalBackgroundColor,
    alignItems: 'center',
  },
  datePickerContainer: {
    height: perfectSize(450),
    width: '85%',
    borderRadius: perfectSize(25),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: perfectSize(225),
  },
  datePickerHeaderContainer: {
    width: '80%',
    height: perfectSize(60),
    backgroundColor: colors.primaryLightColor,
    borderRadius: perfectSize(50),
    position: 'absolute',
    top: perfectSize(-30),
    alignItems: 'center',
    justifyContent: 'center',
  },
  datePickerHeaderLabel: {
    textAlign: 'center',
    color: colors.primary,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(14),
  },
  //Calendar picker styles
  disabledDatesTextStyle: {
    color: colors.backgroundColor,
    opacity: 0.4,
    fontSize: perfectSize(15),
  },
  selectedDayStyle: {
    backgroundColor: colors.primaryLightColor,
    height: perfectSize(30),
    width: perfectSize(30),
  },
  todayTextStyle: {},
  textStyle: {
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
    fontSize: perfectSize(13),
  },
  previousComponent: {
    height: perfectSize(20),
    width: perfectSize(20),
    resizeMode: 'contain',
    tintColor: colors.primaryTintColor,
    opacity: 0.5,
  },
  nextComponent: {
    height: perfectSize(20),
    width: perfectSize(20),
    resizeMode: 'contain',
    tintColor: colors.primaryTintColor,
    opacity: 0.5,
  },
  monthYearHeaderWrapperStyle: {
    flexDirection: 'column',
    alignSelf: 'center',
  },
  yearTitleStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(16),
    opacity: 0.6,
  },
  monthTitleStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(18),
    textTransform: 'uppercase',
  },
  dayLabelsWrapper: {
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  bottomViewContainer: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: perfectSize(-30),
    width: '50%',
    justifyContent: 'space-between',
  },
  seeAllTransactions: {
    alignItems: 'center',
    borderRadius: perfectSize(10),
    marginTop: perfectSize(15),
    padding: '5%',
    backgroundColor: colors.primaryLightColor,
    justifyContent: 'center',
  },
  seeAllTransactionsLabel: {
    color: colors.primary,
    fontSize: perfectSize(16),
    fontFamily: fonts.quicksandBold,
  },
  seeAllTransactionsImage: {
    height: perfectSize(25),
    width: perfectSize(25),
    tintColor: colors.primary,
  },
});
