import {StyleSheet} from 'react-native';
import {colors, fonts, perfectSize, width} from '../../theme';

// eslint-disable-next-line no-undef
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: perfectSize(23),
    backgroundColor: colors.backgroundColor,
  },
  headerContainer: {
    flexDirection: 'row',
    marginTop: perfectSize(10),
  },
  headerTitleContainer: {},
  headerTitle: {
    color: colors.headerTitleColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(30),
  },
  userName: {
    color: colors.headerTitleColor,
    fontFamily: fonts.quicksandRegular,
    fontSize: perfectSize(23),
    marginTop: perfectSize(10),
    letterSpacing: perfectSize(1),
  },
  dashboardContainer: {
    height: '17%',
    width: '100%',
    marginTop: '5%',
    alignSelf: 'center',
    borderRadius: perfectSize(20),
    backgroundColor: colors.primaryCardBackgroundColor,
    // alignItems: 'center',
    justifyContent: 'center',
    // flexDirection: 'row',
    padding: perfectSize(20),
  },
  dashboardHeader: {
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
  },
  dashboardInnerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '5%',
  },
  incomeContainer: {
    height: '100%',
    width: '45%',
    borderRadius: perfectSize(20),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  expenseContainer: {
    height: '100%',
    width: '45%',
    borderRadius: perfectSize(20),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  downArrowContainer: {
    height: perfectSize(50),
    width: perfectSize(50),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(128,237,153,0.2)',
    borderRadius: perfectSize(10),
  },
  downArrow: {
    height: perfectSize(25),
    width: perfectSize(25),
    resizeMode: 'contain',
    tintColor: 'rgb(128,237,153)',
  },
  upArrowContainer: {
    height: perfectSize(50),
    width: perfectSize(50),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: perfectSize(10),
    backgroundColor: 'rgba(255,179,25,0.2)',
  },
  upArrow: {
    tintColor: 'rgb(255,179,25)',
    height: perfectSize(25),
    width: perfectSize(25),
    resizeMode: 'contain',
  },
  dashboardIncomeHeaderStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandRegular,
    fontSize: perfectSize(16),
    opacity: 0.7,
    letterSpacing: perfectSize(0.5),
  },
  dashboardExpenseHeaderStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandRegular,
    fontSize: perfectSize(16),
    opacity: 0.7,
    letterSpacing: perfectSize(0.5),
  },
  dashboardIncomeStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(18),
  },
  dashboardExpenseStyle: {
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(18),
  },
  topCatContainer: {
    width: '100%',
    backgroundColor: colors.primaryCardBackgroundColor,
    borderRadius: perfectSize(20),
    marginTop: '5%',
  },
  topCatHeader: {
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
    padding: perfectSize(20),
  },
  topCatListContainer: {
    paddingBottom: '3.33%',
  },
  expenseCatContainer: {
    alignItems: 'center',
    backgroundColor: colors.primaryCardBackgroundColor,
  },
  //Category list styles
  catContainer: {
    height: perfectSize(200),
    width: '45%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: perfectSize(20),
  },
  catImageContainer: {
    height: perfectSize(70),
    width: perfectSize(70),
    borderRadius: perfectSize(35),
    alignItems: 'center',
    justifyContent: 'center',
  },
  catImage: {
    height: '50%',
    width: '50%',
    resizeMode: 'contain',
    tintColor: colors.primaryLightColor,
  },
  catTitle: {
    marginTop: '20%',
    fontSize: perfectSize(18),
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
  },
  catTotalExpense: {
    // marginTop: '5%',
    fontSize: perfectSize(18),
    color: colors.primaryLightColor,
    fontFamily: fonts.quicksandBold,
  },
});
