/* eslint-disable no-undef */
export default actionTypes = {
  //LOGIN ACTIONS
  UPDATE_LOGIN_EMAIL: 'UPDATE_LOGIN_EMAIL',
  UPDATE_LOGIN_PASSWORD: 'UPDATE_LOGIN_PASSWORD',

  //SIGNUP ACTIONS
  UPDATE_SIGNUP_EMAIL: 'UPDATE_SIGNUP_EMAIL',
  UPDATE_SIGNUP_PASSWORD: 'UPDATE_SIGNIP_PASSWORD',

  //AUTH
  USER_LOGIN: 'USER_LOGIN',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNOUT: 'USER_SIGNOUT',

  //App (Home)
  SET_USER_DATA: 'SET_USER_DATA',
  SET_ALL_EXPENSES: 'SET_ALL_EXPENSES',
  SET_ALL_INCOME: 'SET_ALL_INCOME',
};
