export default actionTypes = {
    //LOGINACTIONS
    UPDATE_LOGIN_EMAIL: 'UPDATE_LOGIN_EMAIL',
    UPDATE_SIGNUP_EMAIL: 'UPDATE_SIGNUP_EMAIL',

    //SIGNUP ACTIONS
    UPDATE_LOGIN_PASSWORD: 'UPDATE_LOGIN_PASSWORD',
    UPDATE_SIGNUP_PASSWORD: 'UPDATE_SIGNIP_PASSWORD',

    //AUTH
    USER_LOGIN: 'USER_LOGIN',
    USER_SIGNUP: 'USER_SIGNUP',
    USER_SIGNOUT: 'USER_SIGNOUT'
}